name: codecov.io

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
              gcc \
              acl \
              libacl1-dev \
              attr \
              libcap2-bin \
              libcap-dev \
              libonig-dev \
              liburing-dev

      - name: Generate coverage
        run: |
          ./configure --enable-gcov EXTRA_CFLAGS="-std=gnu2x"
          make -j$(nproc) check TEST_FLAGS="--sudo"
          gcov -abcfpu obj/*/*.o

      - uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
